# A sample Gemfile
source "https://rubygems.org"

gem 'rake'
gem 'dotenv'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-flash'
gem "sinatra-activerecord"
gem 'will_paginate'
gem 'will_paginate-bootstrap'
gem 'pg'
gem 'thin'

group :development do
  gem 'pry'
  gem 'pry-byebug'
  gem 'shotgun'
end
